[externalServices]

[webSubHubSettings]
URL = "http://localhost:9095/hub"
TOPICS_TO_REGISTER = ["audit","opensearch transaction","opensearch audit"]
RETRY_INTERVAL = 10.0 # in seconds
MAX_RETRIES = 3

[systemInfo]
SYSNAME = "IOL-Ref-Implementaion v0.1"

[ports]
HTTP_LISTENER_PORT = 9093
TCP_LISTENER_PORT = 9094

[[httpRoutes]]
contentType = "application/json"
methods = ["POST"]
path = "^/Patient/\\$match"
target = "http://localhost:9090"
pathPrefix = "/fhir/r4"
workflow = "PATIENT_DEMOGRAPHICS_MATCH"

[[httpRoutes]]
contentType = "application/json"
methods = ["GET"]
path = "^/Patient(.*)"
target = "http://localhost:9090"
pathPrefix = "/fhir/r4"
workflow = "PATIENT_DEMOGRAPHICS_QUERY"

[[httpRoutes]]
contentType = "application/json"
methods = ["POST"]
path = "/Patient"
target = "http://localhost:9090"
pathPrefix = "/fhir/r4"
workflow = "PATIENT_DEMOGRAPHICS_CREATE"

[[httpRoutes]]
contentType = "application/json"
methods = ["PUT"]
path = "^/Patient(.*)"
target = "http://localhost:9090"
pathPrefix = "/fhir/r4"
workflow = "PATIENT_DEMOGRAPHICS_UPDATE"

[[httpRoutes]]
contentType = "application/json"
methods = ["DELETE"]
path = "^/Patient(.*)"
target = "http://localhost:9090"
pathPrefix = "/fhir/r4"
workflow = "PATIENT_DEMOGRAPHICS_DELETE"

[[tcpRoutes]]
HL7Code = "QBP^Q21"
method = "GET"
target = "http://localhost:9090"
pathPrefix = "/fhir/r4"
workflow = "PATIENT_DEMOGRAPHICS_QUERY"

[[tcpRoutes]]
HL7Code = "ADT^A01"
method = "POST"
target = "http://localhost:9090"
pathPrefix = "/fhir/r4"
workflow = "PATIENT_DEMOGRAPHICS_CREATE"

[[tcpRoutes]]
HL7Code = "ADT^A06"
method = "PUT"
target = "http://localhost:9090"
pathPrefix = "/fhir/r4"
workflow = "PATIENT_DEMOGRAPHICS_UPDATE"
