[externalServices]
WEBSUB_HUB_URL = "http://localhost:9095/hub"

[systemInfo]
SYSNAME = "IOL-Ref-Implementaion v0.1"

[ports]
HTTP_LISTENER_PORT=9093
TCP_LISTENER_PORT=9094

[[httpRoutes]]
methods = ["GET"]
path = "^/pdq/.*$"
target = "http://localhost:9092"
contentType = "application/json"
workflow = "PATIENT_DEMOGRAPHICS_QUERY"
# auth = {tokenUrl = "http://localhost:9092/token", clientId = "client_id", clientSecret = "client_secret", scopes = ["scope1", "scope2"]}
# auth = {username = "admin", password = "admin"}

[[httpRoutes]]
methods = ["POST"]
path = "^/pdc/.*$"
target = "http://localhost:9092"
contentType = "application/json"
workflow = "PATIENT_DEMOGRAPHICS_CREATE"
# auth = {tokenUrl = "http://localhost:9092/token", clientId = "client_id", clientSecret = "client_secret", scopes = ["scope1", "scope2"]}
# auth = {username = "admin", password = "admin"}

[[tcpRoutes]]
HL7Code = "QBP^Q21"
method = "GET"
target = "http://localhost:9092"
workflow = "PATIENT_DEMOGRAPHICS_QUERY"

[[tcpRoutes]]
HL7Code = "ADT^A01"
method = "POST"
target = "http://localhost:9092"
workflow = "PATIENT_DEMOGRAPHICS_CREATE"

[[tcpRoutes]]
HL7Code = "ADT^A06"
method = "PUT"
target = "http://localhost:9092"
workflow = "PATIENT_DEMOGRAPHICS_UPDATE"